### ISSUE TITLE
Can't use

### ISSUE THREAD

**Issue by Ella-Alinda** [DyAxy/V2Board_Python_Bot#2]
Hi!
I got an error when running this program. I tried to change the database, change the Python version, and change the MySQL version, but these seem to be useless. He still has an error report. Please help me solve it.
---
My System info
**Debian 11 x86_64
Python 3.10**

```
Connection Error:  can't concat int to bytes
2023-01-08 13:31:58,710 - telegram.ext._application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/root/V2b/Commands/bind.py", line 27, in onQuery
    result = db.sql_query(sql)
  File "/root/V2b/handler.py", line 226, in sql_query
    self.cur.execute(sql)
AttributeError: 'NoneType' object has no attribute 'execute'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/ame/lib/python3.10/site-packages/telegram/ext/_application.py", line 1002, in process_update
    await coroutine
  File "/root/miniconda3/envs/ame/lib/python3.10/site-packages/telegram/ext/_handler.py", line 137, in handle_update
    return await self.callback(update, context)
  File "/root/V2b/Commands/bind.py", line 44, in exec
    user = onQuery(
  File "/root/V2b/Commands/bind.py", line 30, in onQuery
    return result
UnboundLocalError: local variable 'result' referenced before assignment
```

**Comment by DyAxy** [comment]
Check your database information at config.yaml
